#!/usr/bin/env python

from my_utils.args import parseArgs
from my_utils.helpers import isFloat

import random
import sys
import math

def main():
    args = getArgs()

    accumulator = 0.0
    numValues = 0

    for value in args.values:
        accumulator += value
        numValues += 1

    print(accumulator / numValues)


def getArgs():
    argInput = {
        "flags": "input",
        "options": {
            "nargs": "*",
            "default": [],
            "help": "The values to average"
        }
    }

    parserSetup = {
        "description": "Averages values. If no input provided, reads from stdin",
        "args": [
            argInput
        ],
    }

    args = parseArgs(parserSetup)

    #read from stdin if no input supplied
    if(len(args.input) == 0):
        args.input = sys.stdin.read().split()

    #convert to proper list of values
    args.values = [float(line) for line in args.input if isFloat(line)]

    if len(args.values) == 0:
        print("average: must provide at least one value", file=sys.stderr)
        sys.exit()

    return args

if __name__ == '__main__':
    try:
       main()
    except Exception:
        print("average: an error occured", file=sys.stderr)