#!/usr/bin/env python

from my_utils.args import parseArgs
from my_utils.helpers import isFloat

import random
import sys
import math

def main():
    args = getArgs()

    for value in args.input.split(args.delimiter):
        print(value)

def getArgs():
    argDelim = {
        "flags": ["-d", "--delimiter"],
        "options": {
            "default": " ",
            "type": str,
            "dest": "delimiter",
            "help": "Delimiter to use"
        }
    }
    argIgnoreNewlines = {
        "flags": ["-k", "--keep-newlines"],
        "options": {
            "action": "store_true",
            "dest": "keepNewlines",
            "help": "keep newlines from input"
        }
    }
    argInput = {
        "flags": "input",
        "options": {
            "nargs": "?",
            "type": str,
            "default": "",
            "help": "The input string to split on"
        }
    }

    parserSetup = {
        "description": "Splits a string based on delimiter, default is space " ".\
        If no input is specified, it reads values from stdin",
        "args": [
            argDelim,
            argIgnoreNewlines,
            argInput
        ]
    }

    args = parseArgs(parserSetup)

    #read from stdin if no input supplied
    if(len(args.input) == 0):
        args.input = sys.stdin.read()

    if not args.keepNewlines:
        args.input = args.input.replace('\r', '').replace('\n', '')

    return args

if __name__ == '__main__':
    try:
       main()
    except Exception:
        print("delim: an error occured", file=sys.stderr)